name: Scheduled Python Job

on:
  schedule:
    - cron: "0 12 * * *" # Customize as needed
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install selenium beautifulsoup4 webdriver-manager prefect gspread oauth2client python-dotenv; fi

      - name: Set up environment
        run: |
          echo '${{ secrets.ENV_FILE }}' > .env
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Run script
        run: python your_script.py
