name: Scheduled Python Job

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight (00:00)
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Chrome and ChromeDriver
        run: |
          # Install Chrome
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          # Get Chrome version
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "Chrome version: $CHROME_VERSION"
          
          # Install ChromeDriver using the new Chrome for Testing API
          CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE")
          echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
          
          # Download and install ChromeDriver
          wget -O chromedriver-linux64.zip "https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
          # Verify installation
          chromedriver --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install selenium beautifulsoup4 prefect gspread oauth2client python-dotenv; fi

      - name: Set up environment
        run: |
          echo '${{ secrets.ENV_FILE }}' > .env
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

      - name: Run all scripts
        run: |
          python flows/cryptorank.py || echo "CryptoRank failed"
          python flows/ethglobal.py || echo "ETH Global failed"
          python flows/alliance.py || echo "Alliance DAO failed"
          python flows/gitcoin.py || echo "GitCoin failed"
          python flows/devpost.py || echo "GitCoin failed"
          python flows/merge.py || echo "Merge failed"
